# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: rpmbuild/centos7
    steps:
      - checkout
      - package
      - build_rpm

      - store_artifacts:
          path: /home/builder/rpm/noarch
          destination: rpms
      - store_artifacts:
          path: /home/builder/packages
          destination: tarball


commands:
  package:
    steps:
      - run: ./scripts/package.sh
  build_rpm:
    description: build rpm package
    steps:
      - run: rpmbuild -ta --debug /home/builder/packages/bush-rabbit.tgz
